import type { Customer, Invoice, RevenueData } from './types';

export const customers: Customer[] = [
  {
    id: 'cus_1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    avatar: 'https://i.pravatar.cc/150?u=cus_1',
    company: 'Doe Inc.',
    status: 'active',
    amountDue: 1500,
    paymentHistory: 'Paid on time for the last 12 months.',
    accountAgeMonths: 24,
    averageMonthlyBill: 750,
    outstandingBalance: 1500,
  },
  {
    id: 'cus_2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    avatar: 'https://i.pravatar.cc/150?u=cus_2',
    company: 'Smith & Co.',
    status: 'active',
    amountDue: 250,
    paymentHistory: 'One late payment 3 months ago. Otherwise paid on time.',
    accountAgeMonths: 18,
    averageMonthlyBill: 250,
    outstandingBalance: 250,
  },
  {
    id: 'cus_3',
    name: 'Sam Wilson',
    email: 'sam.wilson@example.com',
    avatar: 'https://i.pravatar.cc/150?u=cus_3',
    company: 'Wilson Enterprises',
    status: 'inactive',
    amountDue: 0,
    paymentHistory: 'Account closed. All payments settled.',
    accountAgeMonths: 36,
    averageMonthlyBill: 500,
    outstandingBalance: 0,
  },
  {
    id: 'cus_4',
    name: 'Alice Brown',
    email: 'alice.brown@example.com',
    avatar: 'https://i.pravatar.cc/150?u=cus_4',
    company: 'Brownstone Corp',
    status: 'active',
    amountDue: 5200,
    paymentHistory: 'Frequently late payments over the last 6 months. Multiple reminders sent.',
    accountAgeMonths: 15,
    averageMonthlyBill: 2000,
    outstandingBalance: 5200,
  },
  {
    id: 'cus_5',
    name: 'Bob Johnson',
    email: 'bob.johnson@example.com',
    avatar: 'https://i.pravatar.cc/150?u=cus_5',
    company: 'Johnson Goods',
    status: 'active',
    amountDue: 0,
    paymentHistory: 'New customer, first bill not yet due.',
    accountAgeMonths: 1,
    averageMonthlyBill: 1000,
    outstandingBalance: 0,
  },
];

export const invoices: Invoice[] = [
    { id: 'INV-001', customerId: 'cus_1', customerName: 'John Doe', customerEmail: 'john.doe@example.com', date: '2024-06-01', dueDate: '2024-07-01', amount: 1500, status: 'pending' },
    { id: 'INV-002', customerId: 'cus_2', customerName: 'Jane Smith', customerEmail: 'jane.smith@example.com', date: '2024-06-05', dueDate: '2024-07-05', amount: 250, status: 'pending' },
    { id: 'INV-003', customerId: 'cus_4', customerName: 'Alice Brown', customerEmail: 'alice.brown@example.com', date: '2024-05-15', dueDate: '2024-06-15', amount: 2600, status: 'overdue' },
    { id: 'INV-004', customerId: 'cus_4', customerName: 'Alice Brown', customerEmail: 'alice.brown@example.com', date: '2024-06-15', dueDate: '2024-07-15', amount: 2600, status: 'pending' },
    { id: 'INV-005', customerId: 'cus_1', customerName: 'John Doe', customerEmail: 'john.doe@example.com', date: '2024-05-01', dueDate: '2024-06-01', amount: 1500, status: 'paid' },
    { id: 'INV-006', customerId: 'cus_2', customerName: 'Jane Smith', customerEmail: 'jane.smith@example.com', date: '2024-05-05', dueDate: '2024-06-05', amount: 250, status: 'paid' },
];

export const revenueData: RevenueData[] = [
    { month: 'Jan', revenue: 4000 },
    { month: 'Feb', revenue: 3000 },
    { month: 'Mar', revenue: 5000 },
    { month: 'Apr', revenue: 4500 },
    { month: 'May', revenue: 6000 },
    { month: 'Jun', revenue: 5500 },
];
