import type { Customer, Invoice, RevenueData } from './types';

export const customers: Customer[] = [
  {
    id: 'cus_1',
    name: 'Budi Santoso',
    email: 'budi.santoso@example.com',
    avatar: 'https://i.pravatar.cc/150?u=cus_1',
    company: 'Santoso Jaya',
    status: 'active',
    amountDue: 1500,
    paymentHistory: 'Membayar tepat waktu selama 12 bulan terakhir.',
    accountAgeMonths: 24,
    averageMonthlyBill: 750,
    outstandingBalance: 1500,
  },
  {
    id: 'cus_2',
    name: 'Citra Lestari',
    email: 'citra.lestari@example.com',
    avatar: 'https://i.pravatar.cc/150?u=cus_2',
    company: 'Lestari & Co.',
    status: 'active',
    amountDue: 250,
    paymentHistory: 'Satu pembayaran terlambat 3 bulan yang lalu. Selebihnya bayar tepat waktu.',
    accountAgeMonths: 18,
    averageMonthlyBill: 250,
    outstandingBalance: 250,
  },
  {
    id: 'cus_3',
    name: 'Adi Nugroho',
    email: 'adi.nugroho@example.com',
    avatar: 'https://i.pravatar.cc/150?u=cus_3',
    company: 'Nugroho Enterprises',
    status: 'inactive',
    amountDue: 0,
    paymentHistory: 'Akun ditutup. Semua pembayaran sudah dilunasi.',
    accountAgeMonths: 36,
    averageMonthlyBill: 500,
    outstandingBalance: 0,
  },
  {
    id: 'cus_4',
    name: 'Dewi Anggraini',
    email: 'dewi.anggraini@example.com',
    avatar: 'https://i.pravatar.cc/150?u=cus_4',
    company: 'Anggraini Corp',
    status: 'active',
    amountDue: 5200,
    paymentHistory: 'Sering terlambat membayar selama 6 bulan terakhir. Beberapa pengingat telah dikirim.',
    accountAgeMonths: 15,
    averageMonthlyBill: 2000,
    outstandingBalance: 5200,
  },
  {
    id: 'cus_5',
    name: 'Eko Prasetyo',
    email: 'eko.prasetyo@example.com',
    avatar: 'https://i.pravatar.cc/150?u=cus_5',
    company: 'Prasetyo Goods',
    status: 'active',
    amountDue: 0,
    paymentHistory: 'Pelanggan baru, tagihan pertama belum jatuh tempo.',
    accountAgeMonths: 1,
    averageMonthlyBill: 1000,
    outstandingBalance: 0,
  },
];

export const invoices: Invoice[] = [
    { id: 'INV-001', customerId: 'cus_1', customerName: 'Budi Santoso', customerEmail: 'budi.santoso@example.com', date: '2024-06-01', dueDate: '2024-07-01', amount: 1500, status: 'pending' },
    { id: 'INV-002', customerId: 'cus_2', customerName: 'Citra Lestari', customerEmail: 'citra.lestari@example.com', date: '2024-06-05', dueDate: '2024-07-05', amount: 250, status: 'pending' },
    { id: 'INV-003', customerId: 'cus_4', customerName: 'Dewi Anggraini', customerEmail: 'dewi.anggraini@example.com', date: '2024-05-15', dueDate: '2024-06-15', amount: 2600, status: 'overdue' },
    { id: 'INV-004', customerId: 'cus_4', customerName: 'Dewi Anggraini', customerEmail: 'dewi.anggraini@example.com', date: '2024-06-15', dueDate: '2024-07-15', amount: 2600, status: 'pending' },
    { id: 'INV-005', customerId: 'cus_1', customerName: 'Budi Santoso', customerEmail: 'budi.santoso@example.com', date: '2024-05-01', dueDate: '2024-06-01', amount: 1500, status: 'paid' },
    { id: 'INV-006', customerId: 'cus_2', customerName: 'Citra Lestari', customerEmail: 'citra.lestari@example.com', date: '2024-05-05', dueDate: '2024-06-05', amount: 250, status: 'paid' },
];

export const revenueData: RevenueData[] = [
    { month: 'Jan', revenue: 4000 },
    { month: 'Feb', revenue: 3000 },
    { month: 'Mar', revenue: 5000 },
    { month: 'Apr', revenue: 4500 },
    { month: 'Mei', revenue: 6000 },
    { month: 'Jun', revenue: 5500 },
];
